development:
  adapter: mysql2
  encoding: utf8
  database: roll_dev
  username: root
  password: 'Ghfdlbycr12mysql'

test: &test
  adapter: mysql2
  encoding: utf8
  database: roll_test
  username: root
  password: 'Ghfdlbycr12mysql'

production:
  adapter: mysql2
  encoding: utf8
  database: roll_prod
  username: root
  password: 'Ghfdlbycr12mysql'

cucumber:
  <<: *test
